#!/bin/bash
# Phase 3D: Router Daily Summary — Cron wrapper for proof aggregation
# Usage: bash scripts/router-daily-summary.sh
# Cron: 0 23 * * * bash /path/router-daily-summary.sh

REPO_ROOT="/root/ghq/github.com/E0993599799/tham-oracle"
SCRIPT_DIR="$REPO_ROOT/scripts"
LOGS_DIR="$REPO_ROOT/logs"
TODAY=$(date +%Y-%m-%d)

# Ensure logs directory exists
mkdir -p "$LOGS_DIR"

# Log file
LOG_FILE="$LOGS_DIR/router-summary-${TODAY}.log"

echo "🔄 Router Daily Summary — $(date)" | tee "$LOG_FILE"
echo "" | tee -a "$LOG_FILE"

# Run aggregator
echo "Running proof aggregator for $TODAY..." | tee -a "$LOG_FILE"
python3 "$SCRIPT_DIR/proof-aggregator.py" "$TODAY" 2>&1 | tee -a "$LOG_FILE"

if [ $? -eq 0 ]; then
    echo "" | tee -a "$LOG_FILE"
    echo "✅ Aggregation complete" | tee -a "$LOG_FILE"
    
    # Check if summary files were created
    SUMMARY_DIR="$REPO_ROOT/ψ/memory/resonance"
    if [ -f "$SUMMARY_DIR/router-summary-${TODAY}.md" ]; then
        echo "✅ Summary file created" | tee -a "$LOG_FILE"
        
        # Commit to git if changed
        cd "$REPO_ROOT"
        git add "$SUMMARY_DIR/router-"* 2>/dev/null || true
        
        if git status --porcelain | grep -q "ψ/memory/resonance"; then
            echo "📝 Committing daily summary..." | tee -a "$LOG_FILE"
            git commit -m "chore: Daily router summary for $TODAY

Generated by Phase 3D router-daily-summary.sh
- Stats: router-stats-${TODAY}.json
- Summary: router-summary-${TODAY}.md  
- Insights: router-insights-${TODAY}.json" 2>&1 | tee -a "$LOG_FILE"
            echo "✅ Committed to git" | tee -a "$LOG_FILE"
        else
            echo "ℹ️ No changes to commit" | tee -a "$LOG_FILE"
        fi
    else
        echo "⚠️ Summary file not created" | tee -a "$LOG_FILE"
    fi
else
    echo "" | tee -a "$LOG_FILE"
    echo "❌ Aggregation failed" | tee -a "$LOG_FILE"
    exit 1
fi

echo "" | tee -a "$LOG_FILE"
echo "✅ Daily summary complete: $LOG_FILE" | tee -a "$LOG_FILE"
