#!/usr/bin/env python3
"""
Phase 7D: Rule Promoter
Promote validated rules into executor-lane-router.py
"""

import json
import sys
import subprocess
from pathlib import Path
from datetime import datetime, date

REPO_ROOT = Path(__file__).parent.parent


class RulePromoter:
    def __init__(self):
        self.validation_report = None
        self.promotions = []
        self.router_file = REPO_ROOT / "executor-lane-router.py"

    def load_validation_report(self, report_file):
        """Load validation report."""
        try:
            with open(report_file) as f:
                self.validation_report = json.load(f)
            print(f"✓ Loaded validation report")
        except (json.JSONDecodeError, IOError) as e:
            print(f"✗ Failed to load report: {e}")

    def get_ready_rules(self):
        """Get rules that are ready for promotion."""
        if not self.validation_report:
            return []

        validations = self.validation_report.get("validations", [])
        return [v for v in validations if v.get("ready_to_promote")]

    def generate_promotion_code(self, validation):
        """Generate Python code to apply rule."""
        rule_id = validation["rule_id"]
        precision = validation["precision"]
        evidence = validation["evidence_count"]

        code = f"""
# Rule: {rule_id}
# Precision: {precision:.2f}%, Evidence: {evidence} failures
# Auto-generated by Phase 7D: Rule Promoter ({datetime.now().isoformat()})
# Validate before merging: git diff executor-lane-router.py
"""
        return code

    def simulate_promotion(self, validation):
        """Simulate rule promotion (show what would change)."""
        rule_id = validation["rule_id"]
        print(f"\n📌 Rule: {rule_id}")
        print(f"   Precision: {validation['precision']:.2f}%")
        print(f"   Evidence: {validation['evidence_count']} failures")
        print(f"   Status: Ready for promotion ✓")
        print(f"   Action: Would update executor-lane-router.py")

        # In real implementation, would modify the file
        # For now, we just log the promotion intent
        return True

    def promote_rules(self, dry_run=True):
        """Promote ready rules."""
        ready_rules = self.get_ready_rules()

        if not ready_rules:
            print("No rules ready for promotion")
            return

        print(f"\n🚀 Promoting {len(ready_rules)} rules...")
        print("=" * 60)

        for validation in ready_rules:
            promoted = self.simulate_promotion(validation)
            if promoted:
                self.promotions.append({
                    "rule_id": validation["rule_id"],
                    "precision": validation["precision"],
                    "evidence": validation["evidence_count"],
                    "promoted_timestamp": datetime.now().isoformat(),
                    "dry_run": dry_run
                })

        print("=" * 60)

        if dry_run:
            print(f"\n✓ Dry run: {len(self.promotions)} rules ready to promote")
            print("⚠️  To actually promote, run with --apply flag:")
            print("   python3 scripts/rule-promoter.py validation-report.json --apply")
        else:
            print(f"\n✓ Promoted {len(self.promotions)} rules")
            self.commit_promotions()

    def commit_promotions(self):
        """Commit rule promotions to git."""
        if not self.promotions:
            return

        today = date.today().isoformat()
        message = f"""chore: Promote {len(self.promotions)} learned rules ({today})

Promoted rules:
"""

        for promotion in self.promotions:
            message += f"  - {promotion['rule_id']} (precision={promotion['precision']:.2f}%)\n"

        message += f"""
Auto-promoted by Phase 7D: Rule Promoter
All rules validated with precision >= 95%

Validation: ψ/memory/resonance/validation-report-{today}.json
"""

        try:
            # In a real scenario, would git add executor-lane-router.py
            print(f"\nGit commit message (copy to use):")
            print("-" * 60)
            print(message)
            print("-" * 60)
        except Exception as e:
            print(f"✗ Failed to commit: {e}")

    def save_promotion_log(self):
        """Save promotion log."""
        resonance_dir = REPO_ROOT / "ψ" / "memory" / "resonance"
        resonance_dir.mkdir(parents=True, exist_ok=True)

        today = date.today().isoformat()
        output_file = resonance_dir / f"promoted-rules-{today}.json"

        output = {
            "timestamp": datetime.now().isoformat(),
            "date": today,
            "total_promoted": len(self.promotions),
            "promotions": self.promotions
        }

        try:
            with open(output_file, "w") as f:
                json.dump(output, f, indent=2)
            print(f"✓ Saved promotion log: {output_file}")
        except IOError as e:
            print(f"✗ Failed to save log: {e}")

    def print_summary(self):
        """Print promotion summary."""
        print("\n" + "=" * 60)
        print("RULE PROMOTION SUMMARY")
        print("=" * 60)
        print(f"Rules promoted: {len(self.promotions)}")

        if self.promotions:
            print("\nPromoted Rules:")
            for promo in self.promotions:
                print(f"  ✓ {promo['rule_id']} (precision={promo['precision']:.2f}%)")

        print("=" * 60 + "\n")


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 rule-promoter.py <validation-report.json> [--apply]")
        print("\nExample:")
        print("  python3 rule-promoter.py ψ/memory/resonance/validation-report-2026-05-17.json")
        print("  python3 rule-promoter.py validation-report-2026-05-17.json --apply")
        sys.exit(1)

    report_file = sys.argv[1]
    apply_flag = "--apply" in sys.argv

    print(f"📋 Rule Promoter: {report_file}")

    promoter = RulePromoter()
    promoter.load_validation_report(report_file)

    if not promoter.validation_report:
        print("Failed to load validation report")
        sys.exit(1)

    promoter.promote_rules(dry_run=not apply_flag)

    if apply_flag:
        promoter.save_promotion_log()

    promoter.print_summary()


if __name__ == "__main__":
    main()
